# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  worker

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sid_sq'
    scannerMode: 'Other'
    extraProperties: 
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-DskipTests'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    
- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'Sid_Jf'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "*.jar",
            "target": "sid123"
          }
        ]
      }
    failNoOp: true
    