# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  worker

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-DskipTests'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    

- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'Jfrog_vidya'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "*.jar",
            "target": "sid123"
          }
        ]
      }
    failNoOp: true